<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZuid3ce\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZuid3ce/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZuid3ce.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZuid3ce\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZuid3ce\appProdProjectContainer([
    'container.build_hash' => 'Zuid3ce',
    'container.build_id' => '0f814d98',
    'container.build_time' => 1630965810,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZuid3ce');
